import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { createRequire } from "module";
import { cpSync } from "fs";

const require = createRequire(import.meta.url);

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
  ],
  define: {
    "process.env.NODE_ENV": '"production"',
  },
  plugins: [],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
});

// 自动复制到 Obsidian vault 插件目录（通过环境变量配置，不设则跳过）
const VAULT_PLUGIN_DIR = process.env.OBSIDIAN_VAULT_PLUGIN_DIR;

function copyToVault() {
  if (!VAULT_PLUGIN_DIR) {
    console.log("ℹ️ 未设置 OBSIDIAN_VAULT_PLUGIN_DIR，跳过复制");
    return;
  }
  try {
    cpSync("main.js", `${VAULT_PLUGIN_DIR}/main.js`);
    cpSync("manifest.json", `${VAULT_PLUGIN_DIR}/manifest.json`);
    console.log("✅ 已复制到 Vault 插件目录");
  } catch (e) {
    console.warn("⚠️ 复制到 Vault 失败:", e.message);
  }
}

if (prod) {
  await context.rebuild();
  copyToVault();
  process.exit(0);
} else {
  await context.watch();
}
